export const states = {
    Australia: [
        { code: 'Australian Capital Territory', name: 'Australian Capital Territory' },
        { code: 'New South Wales', name: 'New South Wales' },
        { code: 'Northern Territory', name: 'Northern Territory' },
        { code: 'Queensland', name: 'Queensland' },
        { code: 'South Australia', name: 'South Australia' },
        { code: 'Tasmania', name: 'Tasmania' },
        { code: 'Victoria', name: 'Victoria' },
        { code: 'Western Australia', name: 'Western Australia' },
    ],
    'New Zealand': [
        { code: 'Auckland', name: 'Auckland' },
        { code: 'Bay of Plenty', name: 'Bay of Plenty' },
        { code: 'Canterbury', name: 'Canterbury' },
        { code: 'Gisborne', name: 'Gisborne' },
        { code: 'Hawke\'s Bay', name: 'Hawke\'s Bay' },
        { code: 'Manawatu-Wanganui', name: 'Manawatu-Wanganui' },
        { code: 'Northland', name: 'Northland' },
        { code: 'Otago', name: 'Otago' },
        { code: 'Southland', name: 'Southland' },
        { code: 'Tasman', name: 'Tasman' },
        { code: 'Taranaki', name: 'Taranaki' },
        { code: 'Wellington', name: 'Wellington' },
        { code: 'Waikato', name: 'Waikato' },
        { code: 'West Coast', name: 'West Coast' },
],
    'United States': [
        { code: 'Alabama', name: 'Alabama' },
        { code: 'Alaska', name: 'Alaska' },
        { code: 'Arizona', name: 'Arizona' },
        { code: 'Arkansas', name: 'Arkansas' },
        { code: 'California', name: 'California' },
        { code: 'Colorado', name: 'Colorado' },
        { code: 'Connecticut', name: 'Connecticut' },
        { code: 'Delaware', name: 'Delaware' },
        { code: 'Florida', name: 'Florida' },
        { code: 'Georgia', name: 'Georgia' },
        { code: 'Hawaii', name: 'Hawaii' },
        { code: 'Idaho', name: 'Idaho' },
        { code: 'Illinois', name: 'Illinois' },
        { code: 'Indiana', name: 'Indiana' },
        { code: 'Iowa', name: 'Iowa' },
        { code: 'Kansas', name: 'Kansas' },
        { code: 'Kentucky', name: 'Kentucky' },
        { code: 'Louisiana', name: 'Louisiana' },
        { code: 'Maine', name: 'Maine' },
        { code: 'Maryland', name: 'Maryland' },
        { code: 'Massachusetts', name: 'Massachusetts' },
        { code: 'Michigan', name: 'Michigan' },
        { code: 'Minnesota', name: 'Minnesota' },
        { code: 'Mississippi', name: 'Mississippi' },
        { code: 'Missouri', name: 'Missouri' },
        { code: 'Montana', name: 'Montana' },
        { code: 'Nebraska', name: 'Nebraska' },
        { code: 'Nevada', name: 'Nevada' },
        { code: 'New Hampshire', name: 'New Hampshire' },
        { code: 'New Jersey', name: 'New Jersey' },
        { code: 'New Mexico', name: 'New Mexico' },
        { code: 'New York', name: 'New York' },
        { code: 'North Carolina', name: 'North Carolina' },
        { code: 'North Dakota', name: 'North Dakota' },
        { code: 'Ohio', name: 'Ohio' },
        { code: 'Oklahoma', name: 'Oklahoma' },
        { code: 'Oregon', name: 'Oregon' },
        { code: 'Pennsylvania', name: 'Pennsylvania' },
        { code: 'Rhode Island', name: 'Rhode Island' },
        { code: 'South Carolina', name: 'South Carolina' },
        { code: 'South Dakota', name: 'South Dakota' },
        { code: 'Tennessee', name: 'Tennessee' },
        { code: 'Texas', name: 'Texas' },
        { code: 'Utah', name: 'Utah' },
        { code: 'Vermont', name: 'Vermont' },
        { code: 'Virginia', name: 'Virginia' },
        { code: 'Washington', name: 'Washington' },
        { code: 'West Virginia', name: 'West Virginia' },
        { code: 'Wisconsin', name: 'Wisconsin' },
        { code: 'Wyoming', name: 'Wyoming' },
],
    'Great Britain': [
        { code: 'England', name: 'England' },
        { code: 'Northern Ireland', name: 'Northern Ireland' },
        { code: 'Scotland', name: 'Scotland' },
        { code: 'Wales', name: 'Wales' },
    ],
};


export const countries = {
    //list of countrties
    Australia: 'Australia',
    'New Zealand': 'New Zealand',
    'United States': 'United States',
    'Great Britain': 'United Kingdom',

};
